# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

# Telegram webhook: foydalanuvchi xabarlari shu URL ga POST qilinadi
telegram_webhook:
    path: /webhook/telegram
    controller: App\Controller\TelegramWebhookController::handle
    methods: [POST]
# Telegram ba'zi sozlamalarda /telegram/webhook ishlatiladi â€” bir xil controller
telegram_webhook_alt:
    path: /telegram/webhook
    controller: App\Controller\TelegramWebhookController::handle
    methods: [POST]
